### ISSUE TITLE
curie-map.yaml should be pulled from some versioned dataset

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/scigraph-docker#1]
The configuration build scripts currently pull the curie-map from the master branch of dipper.  Alternatively, this file should be a part of some versioned download and then referenced in this repo or made configurable.

https://github.com/monarch-initiative/dipper/blob/master/dipper/curie_map.yaml

**Comment by TomConlin** [comment]
Maybe we should go a step further and have the whole dipper process a GH release 
https://help.github.com/en/articles/about-releases

**Comment by kshefchek** [comment]
A dipper code release for each data release would be a good.  I had started this and have not maintained it - https://github.com/monarch-initiative/dipper/releases

**Comment by TomConlin** [comment]
Aye, there the rub, it takes precious time to fiddle all the bits.

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/scigraph-docker/commit/ca20fce33234545a3e6972e673f15a54f1bf07c5#diff-0e91761ece323e1e3b1fc529f2b92d0e

**Comment by TomConlin** [comment]
note curie maps corresponding to releases may be found in 
https://archive.monarchinitative.org/<YYYMM>/translationtable/curie_map.yaml
